[package]
name = "performance"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "data_structures"
harness = false

[dependencies]
rand = "0.8"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }